/**
 * Kadro tercih yardımcı fonksiyonları - mock'tan bağımsız
 */

export interface UserPreferenceStats {
  matchId: number;
  teamId: number;
  teamName: string;
  totalUsers: number;
  attackFormation: {
    selected: string;
    stats: { formation: string; percentage: number; count: number }[];
  };
  defenseFormation: {
    selected: string;
    stats: { formation: string; percentage: number; count: number }[];
  };
  playerPositions: {
    position: string;
    positionLabel: string;
    selectedPlayer: { id: number; name: string; percentage: number } | null;
    preferences: {
      playerId: number;
      playerName: string;
      percentage: number;
      count: number;
      isInStartingXI: boolean;
    }[];
  }[];
}

export interface AutoGeneratedSquad {
  matchId: number;
  teamId: number;
  teamName: string;
  attackFormation: { formation: string; percentage: number };
  defenseFormation: { formation: string; percentage: number };
  totalUsers: number;
  positions: {
    position: string;
    positionLabel: string;
    player: { id: number; name: string; number: number };
    preferencePercentage: number;
    totalPreferences: number;
    allPreferences: { playerId: number; playerName: string; percentage: number; count: number }[];
  }[];
}

export function getPreferenceBorderStyle(percentage: number): { color: string; width: number; opacity: number } {
  if (percentage >= 90) return { color: '#1FA2A6', width: 2.5, opacity: 1 };
  if (percentage >= 75) return { color: '#10B981', width: 2, opacity: 0.95 };
  if (percentage >= 60) return { color: '#34D399', width: 1.5, opacity: 0.9 };
  if (percentage >= 40) return { color: 'rgba(100, 116, 139, 0.3)', width: 2, opacity: 0.8 };
  return { color: 'rgba(100, 116, 139, 0.3)', width: 2, opacity: 0.7 };
}

export function getPositionGroupColor(position: string): {
  primary: string;
  secondary: string;
  background: string;
  text: string;
  name: string;
} {
  const pos = position.toUpperCase();
  if (pos === 'GK' || pos === 'G') {
    return { primary: '#C9A44C', secondary: '#D4AF61', background: 'rgba(201, 164, 76, 0.08)', text: '#D4AF61', name: 'Kaleci' };
  }
  if (['CB', 'RB', 'LB', 'RWB', 'LWB', 'SW', 'DEF'].some(p => pos.includes(p))) {
    return { primary: '#64748B', secondary: '#94A3B8', background: 'rgba(100, 116, 139, 0.08)', text: '#94A3B8', name: 'Defans' };
  }
  if (['CDM', 'DM', 'DMF'].some(p => pos.includes(p))) {
    return { primary: '#7C7A9C', secondary: '#9795B5', background: 'rgba(124, 122, 156, 0.08)', text: '#9795B5', name: 'D. Orta Saha' };
  }
  if (['CM', 'MF', 'CMF'].some(p => pos.includes(p))) {
    return { primary: '#1FA2A6', secondary: '#5BBDC0', background: 'rgba(31, 162, 166, 0.08)', text: '#5BBDC0', name: 'Orta Saha' };
  }
  if (['CAM', 'AM', 'AMF', 'RM', 'LM', 'RMF', 'LMF'].some(p => pos.includes(p))) {
    return { primary: '#4CAF7C', secondary: '#6BC294', background: 'rgba(76, 175, 124, 0.08)', text: '#6BC294', name: 'O. Orta Saha' };
  }
  if (['RW', 'LW', 'WF', 'RWF', 'LWF'].some(p => pos.includes(p))) {
    return { primary: '#D97B5C', secondary: '#E69B82', background: 'rgba(217, 123, 92, 0.08)', text: '#E69B82', name: 'Kanat' };
  }
  if (['ST', 'CF', 'FW', 'SS', 'ATT'].some(p => pos.includes(p))) {
    return { primary: '#C75B5B', secondary: '#D88484', background: 'rgba(199, 91, 91, 0.08)', text: '#D88484', name: 'Forvet' };
  }
  return { primary: '#5A6575', secondary: '#7A8699', background: 'rgba(90, 101, 117, 0.08)', text: '#7A8699', name: 'Oyuncu' };
}
