-- Substitution Votes Tablosu
-- Canlı maçlarda topluluk değişiklik oylaması için

CREATE TABLE IF NOT EXISTS substitution_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id BIGINT NOT NULL,
  team_id BIGINT NOT NULL,
  user_id TEXT NOT NULL,
  player_out_id BIGINT NOT NULL,
  player_in_id BIGINT,
  vote_type TEXT NOT NULL CHECK (vote_type IN ('out', 'in')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  UNIQUE(match_id, user_id, player_out_id, vote_type)
);

CREATE INDEX IF NOT EXISTS idx_substitution_votes_match 
  ON substitution_votes(match_id);

CREATE INDEX IF NOT EXISTS idx_substitution_votes_match_team 
  ON substitution_votes(match_id, team_id);

CREATE INDEX IF NOT EXISTS idx_substitution_votes_player_out 
  ON substitution_votes(match_id, player_out_id);

COMMENT ON TABLE substitution_votes IS 'Canlı maçlarda topluluk değişiklik önerileri ve oyları';
COMMENT ON COLUMN substitution_votes.vote_type IS 'out: oyuncunun çıkması isteniyor, in: oyuncunun girmesi isteniyor';
COMMENT ON COLUMN substitution_votes.player_out_id IS 'Çıkması istenen oyuncunun ID si';
COMMENT ON COLUMN substitution_votes.player_in_id IS 'Girmesi istenen oyuncunun ID si (opsiyonel)';

-- Aggregated view for quick access
CREATE OR REPLACE VIEW substitution_vote_counts AS
SELECT 
  match_id,
  team_id,
  player_out_id,
  vote_type,
  COUNT(*) as vote_count,
  MAX(updated_at) as last_vote_at
FROM substitution_votes
GROUP BY match_id, team_id, player_out_id, vote_type;

-- Function to get player vote summary
CREATE OR REPLACE FUNCTION get_player_vote_summary(p_match_id BIGINT, p_team_id BIGINT)
RETURNS TABLE (
  player_id BIGINT,
  out_votes BIGINT,
  in_votes BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    sv.player_out_id as player_id,
    COALESCE(SUM(CASE WHEN sv.vote_type = 'out' THEN 1 ELSE 0 END), 0) as out_votes,
    COALESCE(SUM(CASE WHEN sv.vote_type = 'in' THEN 1 ELSE 0 END), 0) as in_votes
  FROM substitution_votes sv
  WHERE sv.match_id = p_match_id AND sv.team_id = p_team_id
  GROUP BY sv.player_out_id;
END;
$$ LANGUAGE plpgsql;
