/**
 * Mock test stub - Tüm mock fonksiyonlar devre dışı.
 * Test verisi backend TEST_MODE ile test_matches tablosundan gelir (900001-900010).
 */

export const MOCK_TEST_ENABLED = false;

export const MOCK_MATCH_IDS = { GS_FB: 888001, REAL_BARCA: 888002 } as const;

export function isMockTestMatch(_matchId: number): boolean {
  return false;
}

export function getMockUserTeamId(_matchId: number): number | undefined {
  return undefined;
}

export function getMatch1Start(): number {
  return Date.now();
}

export function getMatch2Start(): number {
  return Date.now();
}

export function getMockMatchStatistics(_matchId: number): any {
  return null;
}

export function getMockPlayerStatistics(_matchId: number): any[] | null {
  return null;
}

export function getMockMatchEvents(_matchId: number): any[] {
  return [];
}

export function getMockCommunitySignals(_matchId: number): any {
  return null;
}

export function getMockLineup(_matchId: number): any {
  return null;
}

export const MATCH_1_EVENTS: any[] = [];
export const MATCH_2_EVENTS: any[] = [];

export function computeLiveState(_matchId: number): any {
  return null;
}

export function getUserPreferenceStats(_matchId: number, _teamId: number): import('../utils/squadPreferenceUtils').UserPreferenceStats | null {
  return null;
}

export function generateAutoSquad(
  _matchId: number,
  _teamId: number,
  _startingXI: { player: { id: number; name: string; number: number; pos: string } }[]
): import('../utils/squadPreferenceUtils').AutoGeneratedSquad | null {
  return null;
}
